/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panin.application.form.other;

import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author ricke
 */
public class FormIngresarInsumo extends javax.swing.JPanel {

    /**
     * Creates new form FormIngresarI
     */
    public FormIngresarInsumo() {
        
        initComponents();
        searchHeader21.setBackground(getBackground());
   
//		lb.putClientProperty(FlatClientProperties.STYLE, "" + "font:$h1.font");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchHeader21 = new panin.application.utilities.SearchHeader2();
        formMostrarInsumos1 = new panin.application.form.insumos.FormMostrarInsumos();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formMostrarInsumos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchHeader21, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(searchHeader21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formMostrarInsumos1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify                     
	private javax.swing.JLabel lb;
	private panin.application.utilities.SearchHeader sheader;
	// End of variables declaration                   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panin.application.form.insumos.FormMostrarInsumos formMostrarInsumos1;
    private panin.application.utilities.SearchHeader2 searchHeader21;
    // End of variables declaration//GEN-END:variables
}
