/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panin.application.form.other;

import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author ricke
 */
public class FormIngresarInsumo extends javax.swing.JPanel {

    /**
     * Creates new form FormIngresarI
     */
    public FormIngresarInsumo() {
        initComponents();
//		lb.putClientProperty(FlatClientProperties.STYLE, "" + "font:$h1.font");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchHeader22 = new panin.application.utilities.SearchHeader2();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchHeader22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(searchHeader22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify                     
	private javax.swing.JLabel lb;
	private panin.application.utilities.SearchHeader sheader;
	// End of variables declaration                   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panin.application.utilities.SearchHeader2 searchHeader22;
    // End of variables declaration//GEN-END:variables
}
